In [1]:
import pandas as pd
import numpy as np
import seaborn as sns 
import matplotlib.pyplot as plt

from warnings import filterwarnings
filterwarnings(action='ignore')

from sklearn.model_selection import train_test_split
from sklearn import metrics
from sklearn.svm import SVC

In [2]:
url = 'https://raw.githubusercontent.com/yakushinav/omo/main/data/iris.csv'
data = pd.read_csv(url)
data.head(5)

sepal_length  sepal_width  petal_length  petal_width      species
0           5.1          3.5           1.4          0.2  Iris-setosa
1           4.9          3.0           1.4          0.2  Iris-setosa
2           4.7          3.2           1.3          0.2  Iris-setosa
3           4.6          3.1           1.5          0.2  Iris-setosa
4           5.0          3.6           1.4          0.2  Iris-setosa

In [3]:
train, test = train_test_split(data, test_size = 0.4, stratify = data['species'], random_state = 42)

In [4]:
X_train = train[['sepal_length','sepal_width','petal_length','petal_width']]
y_train = train.species
X_test = test[['sepal_length','sepal_width','petal_length','petal_width']]
y_test = test.species

fn = ['sepal_length','sepal_width','petal_length','petal_width']
cn = data['species'].unique()

In [5]:
linear_svc = SVC(kernel='linear').fit(X_train, y_train)
y_pred=linear_svc.predict(X_test)

In [6]:
y_pred=linear_svc.predict(X_test)

print('accuracy (точность) классификатора',metrics.accuracy_score(y_pred,y_test))

print("матрица ошибок")
print(metrics.confusion_matrix(y_test, y_pred))

accuracy (точность) классификатора 1.0
матрица ошибок
[[20  0  0]
 [ 0 20  0]
 [ 0  0 20]]


In [7]:
new_iris=[1.3, 2.4, 5.6, 3.5]
y_new_iris=linear_svc.predict([new_iris])

print(y_new_iris)

['Iris-virginica']


In [8]:
print(linear_svc.support_vectors_)

[[5.  3.  1.6 0.2]
 [4.8 3.4 1.9 0.2]
 [5.1 3.8 1.9 0.4]
 [5.7 2.6 3.5 1. ]
 [6.7 3.1 4.7 1.5]
 [6.8 2.8 4.8 1.4]
 [6.1 3.  4.6 1.4]
 [6.2 2.2 4.5 1.5]
 [5.9 3.2 4.8 1.8]
 [6.9 3.1 4.9 1.5]
 [6.3 2.5 4.9 1.5]
 [6.  2.7 5.1 1.6]
 [7.2 3.  5.8 1.6]
 [6.2 2.8 4.8 1.8]
 [5.6 2.8 4.9 2. ]
 [6.3 2.5 5.  1.9]
 [6.5 3.2 5.1 2. ]
 [5.9 3.  5.1 1.8]
 [6.  2.2 5.  1.5]]
